[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framwork = "#custom"
  command = "npm run dev:webpack"
  targetPort = 8091
  port = 8090
  publish = "dist"
  autoLaunch = false
