describe('about페이지로 이동',() => {
  it('메인페이지로 접근합니다.', () => {
    cy.visit('/')
    cy.get('header .nav-link.active')
      .contains('Search')
  })  
  it('about페이지로 접근', () => {
    cy.get('header .nav-link')
      .contains('About')
      .click()
    cy.url()
      .should('include', '/about')
    cy.wait(2000)
    cy.get('header .nav-link.active')
      .contains('About')
    cy.get('.name')
      .contains('SUJI')
  })
  it('영화 상세페이지 이동', () => {
    cy.get('header .nav-link')
      .contains('Movie')
      .click()
    cy.wait(2000)
    cy.url()
      .should('include', '/movie')
  })
  it('about 페이지로 이동', () => {
    cy.get('header .user')
      .click()
    cy.url()
      .should('include', '/about')
    cy.wait(2000)
    cy.get('header .nav-link.active')
      .contains('About')
    cy.get('.name')
      .contains('SUJI')
  })
})